#!/usr/bin/env bash
# Shared helpers for playground scenario scripts.
#
# Source this from a scenario script:
#   source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../lib.sh"
# then drive it with init_repo / new_branch / track / commit.
#
# Every scenario is idempotent: init_repo wipes any existing repo of the same
# name and rebuilds it from scratch, so re-running a scenario erases its prior
# state and recreates the exact same shape.

set -euo pipefail

# Root of the playground/ dir (the directory holding this file).
PLAYGROUND_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Generated repos live here (git-ignored; see playground/.gitignore). Override
# with PLAYGROUND_REPOS_DIR to build elsewhere.
REPOS_DIR="${PLAYGROUND_REPOS_DIR:-$PLAYGROUND_DIR/repos}"

# Deterministic identity so commits don't depend on the user's git config.
export GIT_AUTHOR_NAME="Playground"    GIT_AUTHOR_EMAIL="playground@stacksaw.dev"
export GIT_COMMITTER_NAME="Playground" GIT_COMMITTER_EMAIL="playground@stacksaw.dev"

# The repo the helpers currently operate on (set by init_repo).
REPO=""

# Run git scoped to $REPO, with signing off (scratch repos are throwaway).
gitr() { git -C "$REPO" -c commit.gpgsign=false "$@"; }

# (Re)create a fresh repo at an absolute path with a base commit on main, and
# point the helpers at it. Used directly for repos nested inside a monorepo
# tree; init_repo is the convenience wrapper for a top-level repos/<name>.
init_repo_at() {
  REPO="$1"
  rm -rf "$REPO"
  mkdir -p "$REPO"
  gitr init -q -b main
  printf '# %s\n\nScratch repo generated by the playground.\n' "$(basename "$REPO")" \
    > "$REPO/README.md"
  gitr add -A
  gitr commit -q -m "Initial commit"
}

# (Re)create a fresh repo named $1 at $REPOS_DIR/$1 with a base commit on main.
init_repo() { init_repo_at "$REPOS_DIR/$1"; }

# mono_root <abs-root> <marker>... — (re)create a monorepo root directory with
# the given root markers, so detect_monorepo_root() anchors the repos beneath
# it. A marker ending in "/" is created as a directory (e.g. ".repo/"), others
# as empty files (e.g. "WORKSPACE.bazel", "pnpm-workspace.yaml").
mono_root() {
  local root="$1"; shift
  rm -rf "$root"
  mkdir -p "$root"
  local m
  for m in "$@"; do
    case "$m" in
      */) mkdir -p "$root/${m%/}" ;;
      *) : > "$root/$m" ;;
    esac
  done
}

# shape_single_stack — on the current $REPO, build one feature branch with six
# commits on top of main (a single-segment staircase).
shape_single_stack() {
  new_branch "feature" "main"
  track "feature" "main"
  commit "f1.txt" "Add f1: scaffold module"
  commit "f2.txt" "Add f2: core logic"
  commit "f3.txt" "Add f3: error handling"
  commit "f4.txt" "Add f4: tests"
  commit "f5.txt" "Add f5: docs"
  commit "f6.txt" "Add f6: polish"
}

# shape_staircase — on the current $REPO, build the same six changes split into
# a three-step staircase (step-1 → step-2 → step-3), all tracking main.
shape_staircase() {
  new_branch "step-1" "main"; track "step-1" "main"
  commit "f1.txt" "Add f1: scaffold module"
  commit "f2.txt" "Add f2: core logic"
  new_branch "step-2" "step-1"; track "step-2" "main"
  commit "f3.txt" "Add f3: error handling"
  commit "f4.txt" "Add f4: tests"
  new_branch "step-3" "step-2"; track "step-3" "main"
  commit "f5.txt" "Add f5: docs"
  commit "f6.txt" "Add f6: polish"
}

# new_branch <name> [start-point] — create and check out a branch.
new_branch() {
  local name="$1" start="${2:-}"
  if [ -n "$start" ]; then
    gitr checkout -q -b "$name" "$start"
  else
    gitr checkout -q -b "$name"
  fi
}

# track <branch> <upstream-branch> — set <branch>'s upstream so stacksaw groups
# it under that upstream (staircase membership is then derived by ancestry).
track() { gitr branch --quiet --set-upstream-to="$2" "$1" >/dev/null; }

# commit <file> <message> — write a small file and commit it on the current
# branch. Content is derived from the message so each commit shows some churn.
commit() {
  local file="$1" msg="$2"
  printf '// %s\n%s\n' "$file" "$msg" > "$REPO/$file"
  gitr add -A
  gitr commit -q -m "$msg"
}
