#!/usr/bin/env bash
# Shared helpers for playground scenario scripts.
#
# Source this from a scenario script:
#   source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../lib.sh"
# then drive it with init_repo / new_branch / track / commit.
#
# Every scenario is idempotent: init_repo wipes any existing repo of the same
# name and rebuilds it from scratch, so re-running a scenario erases its prior
# state and recreates the exact same shape.

set -euo pipefail

# Root of the playground/ dir (the directory holding this file).
PLAYGROUND_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Generated repos live here (git-ignored; see playground/.gitignore). Override
# with PLAYGROUND_REPOS_DIR to build elsewhere.
REPOS_DIR="${PLAYGROUND_REPOS_DIR:-$PLAYGROUND_DIR/repos}"

# Deterministic identity so commits don't depend on the user's git config.
export GIT_AUTHOR_NAME="Playground"    GIT_AUTHOR_EMAIL="playground@stacksaw.dev"
export GIT_COMMITTER_NAME="Playground" GIT_COMMITTER_EMAIL="playground@stacksaw.dev"

# The repo the helpers currently operate on (set by init_repo).
REPO=""

# Run git scoped to $REPO, with signing off (scratch repos are throwaway).
gitr() { git -C "$REPO" -c commit.gpgsign=false "$@"; }

# (Re)create a fresh repo at an absolute path with a base commit on main, and
# point the helpers at it. Used directly for repos nested inside a monorepo
# tree; init_repo is the convenience wrapper for a top-level repos/<name>.
init_repo_at() {
  REPO="$1"
  rm -rf "$REPO"
  mkdir -p "$REPO"
  gitr init -q -b main
  printf '# %s\n\nScratch repo generated by the playground.\n' "$(basename "$REPO")" \
    > "$REPO/README.md"
  gitr add -A
  gitr commit -q -m "Initial commit"
}

# (Re)create a fresh repo named $1 at $REPOS_DIR/$1 with a base commit on main.
init_repo() { init_repo_at "$REPOS_DIR/$1"; }

# mono_root <abs-root> <marker>... — (re)create a monorepo root directory with
# the given root markers, so detect_monorepo_root() anchors the repos beneath
# it. A marker ending in "/" is created as a directory (e.g. ".repo/"), others
# as empty files (e.g. "WORKSPACE.bazel", "pnpm-workspace.yaml").
mono_root() {
  local root="$1"; shift
  rm -rf "$root"
  mkdir -p "$root"
  local m
  for m in "$@"; do
    case "$m" in
      */) mkdir -p "$root/${m%/}" ;;
      *) : > "$root/$m" ;;
    esac
  done
}

# shape_single_stack — on the current $REPO, build one feature branch with six
# commits on top of main (a single-segment staircase). The commits touch real
# Kotlin so the Diff column exercises syntax highlighting.
shape_single_stack() {
  new_branch "feature" "main"
  track "feature" "main"
  kt_f1 "Add f1: scaffold module"
  kt_f2 "Add f2: core logic"
  kt_f3 "Add f3: error handling"
  kt_f4 "Add f4: tests"
  kt_f5 "Add f5: docs"
  kt_f6 "Polish f6: document Greeter and add shout()"
}

# shape_staircase — on the current $REPO, build the same six changes split into
# a three-step staircase (step-1 → step-2 → step-3), all tracking main.
shape_staircase() {
  new_branch "step-1" "main"; track "step-1" "main"
  kt_f1 "Add f1: scaffold module"
  kt_f2 "Add f2: core logic"
  new_branch "step-2" "step-1"; track "step-2" "main"
  kt_f3 "Add f3: error handling"
  kt_f4 "Add f4: tests"
  new_branch "step-3" "step-2"; track "step-3" "main"
  kt_f5 "Add f5: docs"
  kt_f6 "Polish f6: document Greeter and add shout()"
}

# commit_stdin <file> <msg> — write <file> from this function's stdin, then
# commit it on the current branch. Lets scenarios author multi-line file bodies
# (e.g. Kotlin) with a heredoc while keeping commit() for one-line churn.
commit_stdin() {
  local file="$1" msg="$2"
  mkdir -p "$REPO/$(dirname "$file")"
  cat > "$REPO/$file"
  gitr add -A
  gitr commit -q -m "$msg"
}

# The six shared Kotlin changes used by shape_single_stack / shape_staircase.
# Kept as named steps so both shapes stay in lockstep (six changes, same order).

kt_f1() {
  commit_stdin "src/main/kotlin/demo/Greeter.kt" "$1" <<'KT'
package demo

/** Scaffolding for the demo module. */
class Greeter(private val name: String) {
    fun greet(): String = "Hello, $name!"
}
KT
}

kt_f2() {
  commit_stdin "src/main/kotlin/demo/Stack.kt" "$1" <<'KT'
package demo

/** A tiny immutable stack to exercise core logic and generics. */
sealed class Stack<out T> {
    object Empty : Stack<Nothing>()
    data class Node<out T>(val head: T, val tail: Stack<T>) : Stack<T>()

    fun push(value: @UnsafeVariance T): Stack<T> = Node(value, this)

    val isEmpty: Boolean
        get() = this is Empty
}

fun <T> stackOf(vararg items: T): Stack<T> =
    items.foldRight(Stack.Empty as Stack<T>) { item, acc -> acc.push(item) }
KT
}

kt_f3() {
  commit_stdin "src/main/kotlin/demo/Parser.kt" "$1" <<'KT'
package demo

sealed interface ParseResult<out T> {
    data class Ok<T>(val value: T) : ParseResult<T>
    data class Err(val message: String) : ParseResult<Nothing>
}

/** Error handling via a Result-like type instead of exceptions. */
fun parsePort(raw: String): ParseResult<Int> {
    val n = raw.trim().toIntOrNull()
        ?: return ParseResult.Err("not a number: '$raw'")
    return when (n) {
        in 1..65_535 -> ParseResult.Ok(n)
        else -> ParseResult.Err("port out of range: $n")
    }
}
KT
}

kt_f4() {
  commit_stdin "src/test/kotlin/demo/StackTest.kt" "$1" <<'KT'
package demo

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class StackTest {
    @Test
    fun `push then peek returns last pushed`() {
        val s = stackOf(1, 2, 3)
        assertTrue(s is Stack.Node && s.head == 1)
    }

    @Test
    fun `empty stack is empty`() {
        assertEquals(true, Stack.Empty.isEmpty)
    }
}
KT
}

kt_f5() {
  commit_stdin "src/main/kotlin/demo/Config.kt" "$1" <<'KT'
package demo

/**
 * Application configuration.
 *
 * @property host the bind address, e.g. `0.0.0.0`.
 * @property port a validated TCP port (see [parsePort]).
 * @property tags free-form labels attached to this instance.
 */
data class Config(
    val host: String = "127.0.0.1",
    val port: Int = 8080,
    val tags: List<String> = emptyList(),
) {
    companion object {
        const val DEFAULT_PORT = 8080
    }
}
KT
}

# Unlike f1..f5 (each adds a new file), f6 *modifies* the Greeter.kt created by
# f1 — so the Diff column shows a real modified-file Kotlin diff (opening at the
# first change), not just an added file.
kt_f6() {
  commit_stdin "src/main/kotlin/demo/Greeter.kt" "$1" <<'KT'
package demo

/**
 * Greets people by name.
 *
 * @property name who to greet; defaults to a friendly fallback at the call site.
 */
class Greeter(private val name: String) {
    fun greet(): String = "Hello, $name!"

    /** A louder variant, handy for banners. */
    fun shout(): String = greet().uppercase()
}
KT
}

# new_branch <name> [start-point] — create and check out a branch.
new_branch() {
  local name="$1" start="${2:-}"
  if [ -n "$start" ]; then
    gitr checkout -q -b "$name" "$start"
  else
    gitr checkout -q -b "$name"
  fi
}

# track <branch> <upstream-branch> — set <branch>'s upstream so stacksaw groups
# it under that upstream (staircase membership is then derived by ancestry).
track() { gitr branch --quiet --set-upstream-to="$2" "$1" >/dev/null; }

# commit <file> <message> — write a small file and commit it on the current
# branch. Content is derived from the message so each commit shows some churn.
commit() {
  local file="$1" msg="$2"
  printf '// %s\n%s\n' "$file" "$msg" > "$REPO/$file"
  gitr add -A
  gitr commit -q -m "$msg"
}
