#!/usr/bin/env bash
# Shared helpers for playground scenario scripts.
#
# Source this from a scenario script:
#   source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../lib.sh"
# then drive it with init_repo / new_branch / track / commit.
#
# Every scenario is idempotent: init_repo wipes any existing repo of the same
# name and rebuilds it from scratch, so re-running a scenario erases its prior
# state and recreates the exact same shape.

set -euo pipefail

# Root of the playground/ dir (the directory holding this file).
PLAYGROUND_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Generated repos live here (git-ignored; see playground/.gitignore). Override
# with PLAYGROUND_REPOS_DIR to build elsewhere.
REPOS_DIR="${PLAYGROUND_REPOS_DIR:-$PLAYGROUND_DIR/repos}"

# Deterministic identity so commits don't depend on the user's git config.
export GIT_AUTHOR_NAME="Playground"    GIT_AUTHOR_EMAIL="playground@stacksaw.dev"
export GIT_COMMITTER_NAME="Playground" GIT_COMMITTER_EMAIL="playground@stacksaw.dev"

# The repo the helpers currently operate on (set by init_repo).
REPO=""

# Run git scoped to $REPO, with signing off (scratch repos are throwaway).
gitr() { git -C "$REPO" -c commit.gpgsign=false "$@"; }

# (Re)create a fresh repo named $1 at $REPOS_DIR/$1 with a base commit on main.
init_repo() {
  local name="$1"
  REPO="$REPOS_DIR/$name"
  rm -rf "$REPO"
  mkdir -p "$REPO"
  gitr init -q -b main
  printf '# %s\n\nScratch repo generated by playground/scenarios/%s.sh\n' "$name" "$name" \
    > "$REPO/README.md"
  gitr add -A
  gitr commit -q -m "Initial commit"
}

# new_branch <name> [start-point] — create and check out a branch.
new_branch() {
  local name="$1" start="${2:-}"
  if [ -n "$start" ]; then
    gitr checkout -q -b "$name" "$start"
  else
    gitr checkout -q -b "$name"
  fi
}

# track <branch> <upstream-branch> — set <branch>'s upstream so stacksaw groups
# it under that upstream (staircase membership is then derived by ancestry).
track() { gitr branch --quiet --set-upstream-to="$2" "$1" >/dev/null; }

# commit <file> <message> — write a small file and commit it on the current
# branch. Content is derived from the message so each commit shows some churn.
commit() {
  local file="$1" msg="$2"
  printf '// %s\n%s\n' "$file" "$msg" > "$REPO/$file"
  gitr add -A
  gitr commit -q -m "$msg"
}
